package com.kovhan.design.systems

import androidx.compose.runtime.Composable
import androidx.compose.runtime.Immutable
import androidx.compose.runtime.compositionLocalOf
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.TextUnit
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.kovhan.design.systems.util.getDimensionMultiplier

val LocalDimensions = compositionLocalOf { defaultDimensions }

@Composable
internal fun provideDimensions(): QuotifyDimensions {
    val multiplier = getDimensionMultiplier()

    return defaultDimensions.copy(
        space_2 = defaultDimensions.space_2 * multiplier,
        space_3 = defaultDimensions.space_3 * multiplier,
        space_4 = defaultDimensions.space_4 * multiplier,
        space_5 = defaultDimensions.space_5 * multiplier,
        space_6 = defaultDimensions.space_6 * multiplier,
        space_7 = defaultDimensions.space_7 * multiplier,
        space_8 = defaultDimensions.space_8 * multiplier,
        space_9 = defaultDimensions.space_9 * multiplier,
        space_10 = defaultDimensions.space_10 * multiplier,
        space_11 = defaultDimensions.space_11 * multiplier,
        space_12 = defaultDimensions.space_12 * multiplier,
        space_13 = defaultDimensions.space_13 * multiplier,
        space_14 = defaultDimensions.space_14 * multiplier,
        space_15 = defaultDimensions.space_15 * multiplier,
        space_16 = defaultDimensions.space_16 * multiplier,
        space_17 = defaultDimensions.space_17 * multiplier,
        space_18 = defaultDimensions.space_18 * multiplier,
        space_20 = defaultDimensions.space_20 * multiplier,
        space_22 = defaultDimensions.space_22 * multiplier,
        space_24 = defaultDimensions.space_24 * multiplier,
        space_26 = defaultDimensions.space_26 * multiplier,
        space_27 = defaultDimensions.space_27 * multiplier,
        space_28 = defaultDimensions.space_28 * multiplier,
        space_30 = defaultDimensions.space_30 * multiplier,
        space_32 = defaultDimensions.space_32 * multiplier,
        space_34 = defaultDimensions.space_34 * multiplier,
        space_36 = defaultDimensions.space_36 * multiplier,
        space_37 = defaultDimensions.space_37 * multiplier,
        space_40 = defaultDimensions.space_40 * multiplier,
        space_42 = defaultDimensions.space_42 * multiplier,
        space_48 = defaultDimensions.space_48 * multiplier,
        space_50 = defaultDimensions.space_50 * multiplier,
        space_52 = defaultDimensions.space_52 * multiplier,
        space_60 = defaultDimensions.space_60 * multiplier,
        space_66 = defaultDimensions.space_66 * multiplier,
        space_80 = defaultDimensions.space_80 * multiplier,
        space_90 = defaultDimensions.space_90 * multiplier,
        space_94 = defaultDimensions.space_94 * multiplier,
        space_100 = defaultDimensions.space_100 * multiplier,
        space_150 = defaultDimensions.space_150 * multiplier,
        space_166 = defaultDimensions.space_166 * multiplier,
        space_170 = defaultDimensions.space_170 * multiplier,

        text_spacer_0_2 = defaultDimensions.text_spacer_0_2 * multiplier,
        text_spacer_50_4 = defaultDimensions.text_spacer_50_4 * multiplier,

        line_height_19_6 = defaultDimensions.line_height_19_6 * multiplier,
        line_height_18_85 = defaultDimensions.line_height_18_85 * multiplier,
        line_height_18_2 = defaultDimensions.line_height_18_2 * multiplier,
        line_height_20 = defaultDimensions.line_height_20 * multiplier,
        line_height_22 = defaultDimensions.line_height_22 * multiplier,
        line_height_28_6 = defaultDimensions.line_height_28_6 * multiplier,

        size_0 = defaultDimensions.size_0 * multiplier,
        size_0_5 = defaultDimensions.size_0_5 * multiplier,
        size_1 = defaultDimensions.size_1 * multiplier,
        size_2 = defaultDimensions.size_2 * multiplier,
        size_3 = defaultDimensions.size_3 * multiplier,
        size_4 = defaultDimensions.size_4 * multiplier,
        size_5 = defaultDimensions.size_5 * multiplier,
        size_6 = defaultDimensions.size_6 * multiplier,
        size_8 = defaultDimensions.size_8 * multiplier,
        size_10 = defaultDimensions.size_10 * multiplier,
        size_12 = defaultDimensions.size_12 * multiplier,
        size_14 = defaultDimensions.size_14 * multiplier,
        size_15 = defaultDimensions.size_15 * multiplier,
        size_16 = defaultDimensions.size_16 * multiplier,
        size_18 = defaultDimensions.size_18 * multiplier,
        size_20 = defaultDimensions.size_20 * multiplier,
        size_22 = defaultDimensions.size_22 * multiplier,
        size_24 = defaultDimensions.size_24 * multiplier,
        size_28 = defaultDimensions.size_28 * multiplier,
        size_30 = defaultDimensions.size_30 * multiplier,
        size_32 = defaultDimensions.size_32 * multiplier,
        size_34 = defaultDimensions.size_34 * multiplier,
        size_36 = defaultDimensions.size_36 * multiplier,
        size_38 = defaultDimensions.size_38 * multiplier,
        size_40 = defaultDimensions.size_40 * multiplier,
        size_42 = defaultDimensions.size_42 * multiplier,
        size_44 = defaultDimensions.size_44 * multiplier,
        size_47 = defaultDimensions.size_47 * multiplier,
        size_48 = defaultDimensions.size_48 * multiplier,
        size_50 = defaultDimensions.size_50 * multiplier,
        size_52 = defaultDimensions.size_52 * multiplier,
        size_56 = defaultDimensions.size_56 * multiplier,
        size_57 = defaultDimensions.size_57 * multiplier,
        size_60 = defaultDimensions.size_60 * multiplier,
        size_64 = defaultDimensions.size_64 * multiplier,
        size_70 = defaultDimensions.size_70 * multiplier,
        size_74 = defaultDimensions.size_74 * multiplier,
        size_78 = defaultDimensions.size_78 * multiplier,
        size_84 = defaultDimensions.size_84 * multiplier,
        size_86 = defaultDimensions.size_86 * multiplier,
        size_90 = defaultDimensions.size_90 * multiplier,
        size_92 = defaultDimensions.size_92 * multiplier,
        size_100 = defaultDimensions.size_100 * multiplier,
        size_110 = defaultDimensions.size_110 * multiplier,
        size_120 = defaultDimensions.size_120 * multiplier,
        size_128 = defaultDimensions.size_128 * multiplier,
        size_130 = defaultDimensions.size_130 * multiplier,
        size_132 = defaultDimensions.size_132 * multiplier,
        size_134 = defaultDimensions.size_134 * multiplier,
        size_140 = defaultDimensions.size_140 * multiplier,
        size_142 = defaultDimensions.size_142 * multiplier,
        size_146 = defaultDimensions.size_146 * multiplier,
        size_156 = defaultDimensions.size_156 * multiplier,
        size_160 = defaultDimensions.size_160 * multiplier,
        size_200 = defaultDimensions.size_200 * multiplier,
        size_202 = defaultDimensions.size_202 * multiplier,
        size_228 = defaultDimensions.size_228 * multiplier,
        size_240 = defaultDimensions.size_240 * multiplier,
        size_246 = defaultDimensions.size_246 * multiplier,
        size_250 = defaultDimensions.size_250 * multiplier,
        size_260 = defaultDimensions.size_260 * multiplier,
        size_280 = defaultDimensions.size_280 * multiplier,
        size_288 = defaultDimensions.size_288 * multiplier,
        size_290 = defaultDimensions.size_290 * multiplier,
        size_295 = defaultDimensions.size_295 * multiplier,
        size_310 = defaultDimensions.size_310 * multiplier,
        size_420 = defaultDimensions.size_420 * multiplier,

        screenPadding = defaultDimensions.screenPadding * multiplier,
        screenPaddingDouble = defaultDimensions.screenPaddingDouble * multiplier,
        topBarHeight = defaultDimensions.topBarHeight * multiplier,
        buttonHeight = defaultDimensions.buttonHeight * multiplier,

        corner_radius_15 = defaultDimensions.corner_radius_15 * multiplier,
        corner_radius_12 = defaultDimensions.corner_radius_12 * multiplier,
        corner_radius_10 = defaultDimensions.corner_radius_10 * multiplier,
        corner_radius_8 = defaultDimensions.corner_radius_8 * multiplier,
        corner_radius_6 = defaultDimensions.corner_radius_6 * multiplier,
        corner_radius_4 = defaultDimensions.corner_radius_4 * multiplier,
        corner_radius_2 = defaultDimensions.corner_radius_2 * multiplier,

        size_icon_10 = defaultDimensions.size_icon_10 * multiplier,
        size_icon_13 = defaultDimensions.size_icon_13 * multiplier,
        size_icon_17 = defaultDimensions.size_icon_17 * multiplier,
        size_icon_18 = defaultDimensions.size_icon_18 * multiplier,
        size_icon_20 = defaultDimensions.size_icon_20 * multiplier,
        size_icon_22 = defaultDimensions.size_icon_22 * multiplier,
        size_icon_24 = defaultDimensions.size_icon_24 * multiplier,
        size_icon_28 = defaultDimensions.size_icon_28 * multiplier,
        size_icon_32 = defaultDimensions.size_icon_32 * multiplier,
        size_icon_40 = defaultDimensions.size_icon_40 * multiplier,
        size_icon_50 = defaultDimensions.size_icon_50 * multiplier,

        bottomBarIconSize = defaultDimensions.bottomBarIconSize * multiplier,
        bottomBarMainIconSize = defaultDimensions.bottomBarMainIconSize * multiplier,
        bottomBarDotSize = defaultDimensions.bottomBarDotSize * multiplier,
        bottomBarBottomPadding = defaultDimensions.bottomBarBottomPadding * multiplier,
        bottomBarTopPadding = defaultDimensions.bottomBarTopPadding * multiplier,
        bottomBarDotPadding = defaultDimensions.bottomBarDotPadding * multiplier,
        bottomBarHeight = defaultDimensions.bottomBarHeight * multiplier,

        balanceCardCollapsedHeight = defaultDimensions.balanceCardCollapsedHeight * multiplier,
        navigationToolbarHeight = defaultDimensions.navigationToolbarHeight * multiplier,

        snackbarBottomPadding = defaultDimensions.snackbarBottomPadding * multiplier,

        loaderSize = defaultDimensions.loaderSize * multiplier,
    )
}

@Suppress("PropertyName")
@Immutable
data class QuotifyDimensions(
    val space_0: Dp = 0.dp,
    val space_1: Dp = 1.dp,
    val space_2: Dp = 2.dp,
    val space_3: Dp = 3.dp,
    val space_4: Dp = 4.dp,
    val space_5: Dp = 5.dp,
    val space_6: Dp = 6.dp,
    val space_7: Dp = 7.dp,
    val space_8: Dp = 8.dp,
    val space_9: Dp = 9.dp,
    val space_10: Dp = 10.dp,
    val space_11: Dp = 11.dp,
    val space_12: Dp = 12.dp,
    val space_13: Dp = 13.dp,
    val space_14: Dp = 14.dp,
    val space_15: Dp = 15.dp,
    val space_16: Dp = 16.dp,
    val space_17: Dp = 17.dp,
    val space_18: Dp = 18.dp,
    val space_20: Dp = 20.dp,
    val space_22: Dp = 22.dp,
    val space_24: Dp = 24.dp,
    val space_26: Dp = 26.dp,
    val space_27: Dp = 27.dp,
    val space_28: Dp = 28.dp,
    val space_30: Dp = 30.dp,
    val space_32: Dp = 32.dp,
    val space_34: Dp = 34.dp,
    val space_36: Dp = 36.dp,
    val space_37: Dp = 37.dp,
    val space_40: Dp = 40.dp,
    val space_42: Dp = 42.dp,
    val space_48: Dp = 48.dp,
    val space_50: Dp = 50.dp,
    val space_52: Dp = 52.dp,
    val space_60: Dp = 60.dp,
    val space_66: Dp = 66.dp,
    val space_80: Dp = 80.dp,
    val space_90: Dp = 90.dp,
    val space_94: Dp = 94.dp,
    val space_100: Dp = 100.dp,
    val space_150: Dp = 150.dp,
    val space_166: Dp = 166.dp,
    val space_170: Dp = 170.dp,

    val text_spacer_0_2: TextUnit = 0.2.sp,
    val text_spacer_0_07: TextUnit = 0.07.sp,
    val text_spacer_0_15: TextUnit = 0.15.sp,
    val text_spacer_minus_0_2: TextUnit = (-0.4).sp,
    val text_spacer_minus_0_24: TextUnit = (-0.24).sp,
    val text_spacer_minus_0_41: TextUnit = (-0.41).sp,
    val text_spacer_50_4: TextUnit = 50.4.sp,

    val line_height_16: TextUnit = 16.sp,
    val line_height_12: TextUnit = 12.sp,
    val line_height_19_2: TextUnit = 19.2.sp,
    val line_height_19_6: TextUnit = 19.6.sp,
    val line_height_18_85: TextUnit = 18.85.sp,
    val line_height_18_2: TextUnit = 18.2.sp,
    val line_height_16_8: TextUnit = 16.8.sp,
    val line_height_20: TextUnit = 20.sp,
    val line_height_22: TextUnit = 22.sp,
    val line_height_22_4: TextUnit = 22.4.sp,
    val line_height_28_6: TextUnit = 28.6.sp,
    val line_height_33_6: TextUnit = 33.6.sp,
    val line_height_9_38: TextUnit = 9.38.sp,
    val line_height_50_4: TextUnit = 50.4.sp,

    val size_0: Dp = 0.dp,
    val size_0_5: Dp = 0.5.dp,
    val size_1: Dp = 1.dp,
    val size_2: Dp = 2.dp,
    val size_3: Dp = 3.dp,
    val size_4: Dp = 4.dp,
    val size_5: Dp = 5.dp,
    val size_6: Dp = 6.dp,
    val size_8: Dp = 8.dp,
    val size_10: Dp = 10.dp,
    val size_12: Dp = 12.dp,
    val size_14: Dp = 14.dp,
    val size_15: Dp = 15.dp,
    val size_16: Dp = 16.dp,
    val size_18: Dp = 18.dp,
    val size_20: Dp = 20.dp,
    val size_22: Dp = 22.dp,
    val size_24: Dp = 24.dp,
    val size_28: Dp = 28.dp,
    val size_30: Dp = 30.dp,
    val size_31: Dp = 31.dp,
    val size_32: Dp = 32.dp,
    val size_34: Dp = 34.dp,
    val size_36: Dp = 36.dp,
    val size_38: Dp = 38.dp,
    val size_40: Dp = 40.dp,
    val size_42: Dp = 42.dp,
    val size_44: Dp = 44.dp,
    val size_47: Dp = 47.dp,
    val size_48: Dp = 48.dp,
    val size_50: Dp = 50.dp,
    val size_52: Dp = 52.dp,
    val size_56: Dp = 56.dp,
    val size_57: Dp = 57.dp,
    val size_60: Dp = 60.dp,
    val size_64: Dp = 64.dp,
    val size_70: Dp = 70.dp,
    val size_74: Dp = 74.dp,
    val size_78: Dp = 78.dp,
    val size_84: Dp = 84.dp,
    val size_86: Dp = 86.dp,
    val size_90: Dp = 90.dp,
    val size_92: Dp = 92.dp,
    val size_97: Dp = 97.dp,
    val size_100: Dp = 100.dp,
    val size_110: Dp = 110.dp,
    val size_120: Dp = 120.dp,
    val size_128: Dp = 128.dp,
    val size_130: Dp = 130.dp,
    val size_132: Dp = 132.dp,
    val size_134: Dp = 134.dp,
    val size_156: Dp = 156.dp,
    val size_140: Dp = 140.dp,
    val size_142: Dp = 142.dp,
    val size_146: Dp = 146.dp,
    val size_160: Dp = 160.dp,
    val size_200: Dp = 200.dp,
    val size_202: Dp = 202.dp,
    val size_228: Dp = 228.dp,
    val size_230: Dp = 230.dp,
    val size_236: Dp = 236.dp,
    val size_240: Dp = 240.dp,
    val size_246: Dp = 246.dp,
    val size_250: Dp = 250.dp,
    val size_252: Dp = 252.dp,
    val size_254: Dp = 254.dp,
    val size_256: Dp = 256.dp,
    val size_260: Dp = 260.dp,
    val size_280: Dp = 280.dp,
    val size_288: Dp = 288.dp,
    val size_290: Dp = 290.dp,
    val size_295: Dp = 295.dp,
    val size_310: Dp = 310.dp,
    val size_420: Dp = 420.dp,

    val size_original_56: Dp = 56.dp,
    val size_original_86: Dp = 86.dp,
    val size_original_92: Dp = 92.dp,
    val size_original_142: Dp = 142.dp,

    val screenPadding: Dp = 16.dp,
    val screenPaddingDouble: Dp = 32.dp,
    val topBarHeight: Dp = 56.dp,
    val buttonHeight: Dp = 50.dp,

    val corner_radius_20: Dp = 20.dp,
    val corner_radius_15: Dp = 15.dp,
    val corner_radius_12: Dp = 12.dp,
    val corner_radius_10: Dp = 10.dp,
    val corner_radius_8: Dp = 8.dp,
    val corner_radius_6: Dp = 6.dp,
    val corner_radius_4: Dp = 4.dp,
    val corner_radius_2: Dp = 2.dp,

    val size_icon_10: Dp = 10.dp,
    val size_icon_13: Dp = 13.dp,
    val size_icon_17: Dp = 17.dp,
    val size_icon_18: Dp = 18.dp,
    val size_icon_20: Dp = 20.dp,
    val size_icon_22: Dp = 22.dp,
    val size_icon_24: Dp = 24.dp,
    val size_icon_28: Dp = 28.dp,
    val size_icon_32: Dp = 32.dp,
    val size_icon_38: Dp = 38.dp,
    val size_icon_40: Dp = 40.dp,
    val size_icon_50: Dp = 50.dp,

    val bottomBarIconSize: Dp = 24.dp,
    val bottomBarMainIconSize: Dp = 48.dp,
    val bottomBarDotSize: Dp = 6.dp,
    val bottomBarBottomPadding: Dp = 10.dp,
    val bottomBarTopPadding: Dp = 6.dp,
    val bottomBarDotPadding: Dp = 8.dp,
    val bottomBarHeight: Dp = 62.dp,

    val balanceCardCollapsedHeight: Dp = 86.dp,
    val navigationToolbarHeight: Dp = 60.dp,

    val snackbarBottomPadding: Dp = 36.dp,

    val loaderSize: Dp = 52.dp,
)

val defaultDimensions = QuotifyDimensions()
