package com.kovhan.core.analytics

abstract class AnalyticsEvent(
    val name: String,
    val params: Map<String, Any> = emptyMap(),
)

object AnalyticsParam {
    const val REASON = "reason"
    const val TYPE = "type"
    const val RESULT = "result"
    const val PRODUCT = "product"
    const val STATUS = "status"
    const val FAILURE = "failure"
    const val STEP = "step"
    const val NAME = "name"
    const val QUOTE_ID = "quote_id"
    const val QUOTE_COUNT = "quote_count"
    const val COLLECTION_COUNT = "collection_count"
    const val CHANGE_FROM = "change_from"
    const val CHANGE_TO = "change_to"
    const val CHANGED_NAME = "changed_name"
    const val CHANGED_ICON = "changed_icon"
    const val CHANGED_COLOR = "changed_color"
    const val INPUT_METHOD = "input_method"
    const val TEXT_LENGTH = "text_length"
    const val DURATION_SECONDS = "duration_seconds"
    const val EDIT = "edit"
    const val PERMISSION = "permission"
    const val HAS_AUTHOR = "has_author"
    const val HAS_BOOK = "has_book"
    const val TAGS_COUNT = "tags_count"
    const val WIDGET_ENABLED = "widget_enabled"
    const val PUSH_ENABLED = "push_enabled"
    const val SUGGESTED_TAGS_COUNT = "suggested_tags_count"
    const val ACCEPTED_TAGS_COUNT = "accepted_tags_count"
    const val TEXT = "text"
    const val FROM = "from"
    const val TO = "to"
    const val WIDGET_ADDED = "widget_added"
    const val SUBSCRIPTION = "subscription"
    const val LIFE_DAYS = "life_days"
    const val THEME = "theme"
    const val LANGUAGE = "language"
    const val HAS_WIDGET = "has_widget"
    const val AUTH_TYPE = "auth_type"

    const val SURVEY_ID = "survey_id"
    const val QUESTION_ID = "question_id"
    const val OPTIONS_COUNT = "options_count"
    const val HAS_COMMENT = "has_comment"
    const val REWARD_ID = "reward_id"
    const val COMPLETED_SURVEYS = "completed_surveys"
    const val ANSWERED_COUNT = "answered_count"

    const val WIDGET_TYPE = "type"
    const val BACKGROUND_COLOUR = "background_colour"
    const val BACKGROUND = "background"
    const val BACKGROUND_BLUR = "background_blur"
    const val BORDER = "border"
    const val BORDER_COLOUR = "border_colour"
    const val FONT_SIZE = "font_size"
    const val TEXT_COLOUR = "text_colour"
    const val TEXT_ALIGNMENT = "text_alignment"
    const val QUOTE_SOURCE = "quote_sourse"
    const val ADD_DAILY_QUOTE = "add_daily_quote"
    const val REFRESH = "refresh"
}
